### ISSUE TITLE
Experiments with LDM

### ISSUE THREAD

**Issue by RachelTeamo** [forever208/ADM-ES#1]
Thank you for the open source! I see that in 5.5 of the paper, experiments are performed on the LDM, will you open source this part of the code?

**Comment by forever208** [comment]
@RachelTeamo Sure, I can release the code on LDM soon, will let you know once it's done

**Comment by RachelTeamo** [comment]
Okay, I'm looking forward to it. Thanks~

**Comment by forever208** [comment]
@RachelTeamo code of LDM-ES is available now at https://github.com/forever208/LDM-ES

**Comment by RachelTeamo** [comment]
OK, Thanks again~
